In [8]:
import sys
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import gender_guesser.detector as gender
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

In [9]:
genuine_users = pd.read_csv("data/users.csv")
fake_users = pd.read_csv("data/fusers.csv")
# print genuine_users.columns
# print genuine_users.describe()
#print fake_users.describe()
x=pd.concat([genuine_users,fake_users])   
y=len(fake_users)*[0] + len(genuine_users)*[1]
x.dtypes

id                                      int64
name                                   object
screen_name                            object
statuses_count                          int64
followers_count                         int64
friends_count                           int64
favourites_count                        int64
listed_count                            int64
created_at                             object
url                                    object
lang                                   object
time_zone                              object
location                               object
default_profile                       float64
default_profile_image                 float64
geo_enabled                           float64
profile_image_url                      object
profile_banner_url                     object
profile_use_background_image          float64
profile_background_image_url_https     object
profile_text_color                     object
profile_image_url_https                object
profile_sidebar_border_color           object
profile_background_tile               float64
profile_sidebar_fill_color             object
profile_background_image_url           object
profile_background_color               object
profile_link_color                     object
utc_offset                            float64
protected                             float64
verified                              float64
description                            object
updated                                object
dataset                                object
dtype: object

In [10]:
def predict_sex(name):
    sex_predictor=gender.Detector(case_sensitive=False)
    first_name=name.str.split(' ').str.get(0)
    sex=first_name.apply(sex_predictor.get_gender)
    sex_dict={'female':-2,'mostly_female':-1,'unknown':0,'mostly_male':1,'male':2,'andy':3}
    sex_code=sex.map(sex_dict).astype(int)
    return(sex_code)

In [11]:
lang_list = list(enumerate(np.unique(x['lang']))) #it assigns an index starting from 0 to unique values of lang column
lang_dict = { name : i for i, name in lang_list } #list is converted to dictionary use type() to check
x.loc[:,'lang_code'] = x['lang'].map( lambda x: lang_dict[x]).astype(int) # it creates a new column lang_code and map the values
sex_predictor = gender.Detector(case_sensitive=False)
x.loc[:,'sex_code']=predict_sex(x['name'])
feature_columns_to_use = ['statuses_count','followers_count','friends_count','favourites_count','listed_count','sex_code','lang_code']
x=x.loc[:,feature_columns_to_use]
x

,statuses_count,followers_count,friends_count,favourites_count,listed_count,sex_code,lang_code
0,20370,5470,2385,145,52,2,5
1,3131,506,381,9,40,-2,1
2,4024,264,87,323,16,0,1
3,40586,640,622,1118,32,0,1
4,2016,62,64,13,0,2,5
5,3603,138,179,53,1,2,5
6,1183,128,168,2,5,0,1
7,6194,1062,1770,597,5,2,5
8,10962,23368,958,590,715,2,1
9,10947,760,712,693,27,2,5
10,2754,477,218,224,13,-2,5
11,26713,1390,1177,914,68,0,1
12,4111,314,338,47,8,2,5
13,1441,97,203,25,2,2,5
14,1698,289,1930,45,3,0,5
15,402,93,78,36,4,2,5
16,16935,2242,918,44,124,-2,1
17,9437,689,891,199,37,0,5
18,3742,505,571,100,3,0,5
19,770,81,181,89,2,-2,5
20,1430,128,371,204,1,2,5
21,6996,899,305,346,28,-2,1
22,3284,375,1039,1,8,0,1
23,160,46,146,22,0,2,3
24,292,57,110,5,0,2,1
25,5876,616,647,1061,29,0,5
26,7534,1132,1096,6,52,-2,1
27,1294,254,276,89,8,2,5
28,6340,298,419,5,15,2,1
29,5472,6352,3873,65,11,2,5
...,...,...,...,...,...,...,...
1307,0,0,17,0,0,-2,1
1308,2,1,21,0,0,-2,1
1309,0,0,20,0,0,-2,1
1310,2,1,8,0,0,3,1
1311,3,0,15,0,0,-2,1
1312,1,0,17,0,0,-1,1
1313,3,0,16,0,0,-2,1
1314,1,2,19,0,0,2,1
1315,2,2,15,0,0,-2,1
1316,1,1,17,0,0,-2,1
1317,1,2,20,0,0,-2,1
1318,2,0,15,0,0,0,1
1319,2,1,20,0,0,-2,1
1320,2,1,14,0,0,3,1
1321,1,0,18,0,0,-2,1
1322,1,2,15,0,0,-2,1
1323,2,2,15,0,0,-2,1
1324,2,1,18,0,0,-2,1
1325,3,1,22,0,0,2,1
1326,2,0,18,0,0,-2,1
1327,2,0,22,0,0,0,1
1328,2,0,24,0,0,2,1
1329,1,1,12,0,0,2,1
1330,1,1,21,0,0,-2,1
1331,2,1,19,0,0,0,1
1332,1,0,17,0,0,-2,1
1333,0,1,17,0,0,2,1
1334,2,0,15,0,0,-2,1
1335,2,0,16,0,0,-2,1
1336,0,0,17,0,0,-2,1

In [5]:
X_train,X_test,y_train,y_test = train_test_split(x, y, test_size=0.25, random_state=44)

In [16]:
def Using_random_Classifier(X_train,y_train,X_test):
    clf1=RandomForestClassifier(n_estimators=100)
    clf1.fit(X_train,y_train)
    y_pred=clf1.predict(X_test)
    return(accuracy_score(y_test, y_pred))

In [17]:
def Using_Support_Vector(X_train,y_train,X_test):
    clf2=SVC()
    clf2.fit(X_train,y_train)
    y_pred=clf2.predict(X_test)
    return(accuracy_score(y_test, y_pred))

In [18]:
RC_score=Using_random_Classifier(X_train,y_train,X_test)
SVM_score=Using_Support_Vector(X_train,y_train,X_test)

In [19]:
RC_score

0.9432624113475178

In [20]:
SVM_score

0.7702127659574468